
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-spa-sarmadabualkaz-io-v1-scheduledpodautoscaler
  failurePolicy: Fail
  name: mscheduledpodautoscaler.kb.io
  rules:
  - apiGroups:
    - autoscaling.spa.sarmadabualkaz.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledpodautoscalers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-autoscaling-spa-sarmadabualkaz-io-v1-scheduledpodautoscaler
  failurePolicy: Fail
  name: vscheduledpodautoscaler.kb.io
  rules:
  - apiGroups:
    - autoscaling.spa.sarmadabualkaz.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledpodautoscalers
