# spa #1 - manage regular deployments
apiVersion: autoscaling.spa.sarmadabualkaz.io/v1
kind: ScheduledPodAutoscaler
metadata:
  name: scheduledpodautoscaler-sample
spec:
  # Add fields here
  resource:
    type: Deployment
    name: deploy-test
  scaleUp:
    time: 8:15AM
    value: 20
  scaleDown:
    time: 10:00PM
    value: 5
---
#  spa #2 - manage regular deployments - differnent ns
apiVersion: autoscaling.spa.sarmadabualkaz.io/v1
kind: ScheduledPodAutoscaler
metadata:
  name: scheduledpodautoscaler-sample2
  namespace: spa-test
spec:
  # Add fields here
  resource:
    type: Deployment
    name: deploy-test2
  scaleUp:
    time: 8:15AM
    value: 12
  scaleDown:
    time: 4:30PM
    value: 5
---
# spa #3 -  manage regular hpa
apiVersion: autoscaling.spa.sarmadabualkaz.io/v1
kind: ScheduledPodAutoscaler
metadata:
  name: scheduledpodautoscaler-hpa-sample
spec:
  # Add fields here
  resource:
    type: HPA
    name: hpa-test
  scaleUp:
    time: 8:15AM
    value: 20
  scaleDown:
    time: 4:30PM
    value: 4
---
# # spa #4 -  manage regular hpaOperator/annotated deployments
# apiVersion: autoscaling.spa.sarmadabualkaz.io/v1
# kind: ScheduledPodAutoscaler
# metadata:
#   name: scheduledpodautoscaler-hpa-sample
# spec:
#   # Add fields here
#   resource:
#     type: annotatedDeployment
#     name: hpaOperator-test
#   scaleUp:
#     time: 8:15AM
#     value: 14
#   scaleDown:
#     time: 10:30PM
#     value: 7
# ---
